# Generated by Django 3.2.9 on 2021-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=13)),
                ('Passwort', models.CharField(max_length=30)),
            ],
        ),
    ]
