# Generated by Django 3.2.9 on 2021-12-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Passwort',
            new_name='Password',
        ),
    ]
