# Generated by Django 3.2.9 on 2021-12-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_passwort_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
